baseURL = "https://mohamedmcn.github.io/WBC/"
#baseURL = "https://localhost/"
#baseURL = "https://mohamedcamara.infenlaces.com/hugo/docs/"
defaultContentLanguage = "es"
title = "My New Hugo Site"
theme = "learn"
disableLandingPage= "true"
[outputs]
home=[ "HTML", "RSS", "JSON"]
[params]
themeVariant = "green"
[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10
[[menu.shortcuts]] 
name = "<i class='fas fa-dumbbell'></i> WBC"
identifier = "wbc"
url = "https://wbcboxing.com/en/"
weight = 11





[Languages]
[Languages.en]
title = "World boxing council"
weight = 1
languageName = "English"

[Languages.es]
title = "consejo mundial de boxeon"
weight = 2
languageName = "Español"

[Languages.fr]
title = "Conseil mondial de boxe"
weight = 3
languageName = "Français"

